name: Deploy

# Trigger the workflow on push and
# pull request events on the master branch
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test


  # security-check:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   # defaults:
  #   #   run:
  #   #     working-directory: ./quiz-app
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Run Snyk to check for vulnerabilities
  #       uses: snyk/actions/node@master
  #       continue-on-error: true # To make sure that SARIF upload gets called
  #       env:
  #         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
  #     - name: Install Snyk CLI
  #       uses: snyk/actions/setup@master
  #       # with:
  #       #   version: latest
  #       env:
  #         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  
          
  #     - name: Snyk Authenticate    
  #       run: snyk auth ${{ secrets.SNYK_TOKEN }}

  #     - name: Snyk Code Test
  #       run: snyk code test --all-projects
  #       continue-on-error: true

  deploy:
    needs: test